@MuscleMemory.API_HostAddress = https://localhost:7002
@token = CfDJ8D9A3ke8Dp5Gud4dAM-ciC-CQ1I_g_H0lhhQaaNVQpQakVD2Y9jSFlAESvGgPm6yE7W-YW6b7uyb0bTY_Hdreqpe8LFpNLoD3EVfg1SqDB0fHkAlDJwS5x4Z9udHA_az8aToVHpdgbANdmM3Q79TDQ8KAw49Hojs5TA0yxb9kFJTa3-NHPFbR0nNWmU5nL2MtAW5zJo5cCzMjvApnEQpFkgPdJQu8wW495aQ-zK2uEEezgl79L0hcPdkZHFbC45VRFLDs0VXfmjJeY3q__9DW5qpCx7GkgRpOwaEcLEJ7LlbCMVe_hVu8H22AvhwDvJoTHH-imXwKHPUgw6caO44CMNBX8JjdTm-uRQfGZRYxlR5rX28lCD5ZnRRkcN5FbtSIIAj0JGOP8KHo-XiRlqlnfYgdO1tgH-3GhaQWdm69ndfJ5Mj6pZfCw0axmQogSjC65-svgcQzT0f2uv7CLXp9vZ3nJvFiUunZrvvO13IHQQ-CFTG-JQbJqwVyN7vaQV9A0lfqrwlSBmgJIt2WiVSpn7SXmMlGWkXTgB-NzZAmtTiEU12OGrqqybjLToprMaALOl7WBeKx_6XejElV_Q8H0s5tTiom_aybumWfFfpoAkWLeHFdlb1R3I20RMZyD8m0H7DtgiMQ7TdbCgafh5E8khKRiqOUdrXbzoZwnGQjnsNkyxNQ47fdjb6ra5WCsNKog
@token2 = CfDJ8D9A3ke8Dp5Gud4dAM-ciC9bxFenSUUs_mm_hXcvb477yfFdc8q-yY1sw-ZjJl7d-f_qANXvL7A53kbZ8XaG3ZSYUa_-bA19EBkNe-oHSdFjNlGIeTjHszp4cLkPCOQrXunCrdpD1spZ1j1e8Gpxwm0u5Jm9GeeoQv5tGv7RxE7j5h1b-DLPhlCFdNIuTDgd188R7xmGy0FEFJX05ckHeQKwW6UO3Pv1xvbHNAmfLuDjhF_P7-dnP8SntXDraMSfh1m2wV-ZPbNh8xRPpzU_Ig0vuxXKj7Kd8hnsAus6CarmJ_YmQpDdE8MFECNqLj11BOuvQKY2pfPaCGq--xpM6JkJ4DR74-x-RXcWkLFDbi0gSr3Tni5ukHEhwgTfjD9mmfGsLamUwURKKmSr_StYP4PDofRbj14qI9QAnwLaLaG-PqNrQQW0U8qhYQxjBQG0M1pMhaFI_ChO02lDNmtvo4bTA2EhdIjM0Yqg8DHtkh1NxdVB5K85To0G3jafmj3tXT1D5BNOF28X7u7L9OLzjz9UORDpuvyRTKW88y8I27vJvVjFmnMgkb1IPzjDs3wbyQ2hQiIgJkSxCZ--krp_alRY6MHi95AVAWszu4nfNmf8KJ2AAR9CFrUf1nH6tBGsh5jBlM9q16xLsUym8tTJdiStWfBRxl8btNs6v9HfzHhNb0DFGxYn1E3Kc500Tg18Zw
@tokenAdmin = CfDJ8D9A3ke8Dp5Gud4dAM-ciC_nAwkShZYl_P4VF10E96PfQaHccVZM311TqT78lbEqJUvTyM7Rn5VGYdCpzHfGjuDCIXXA4vSHb_xmMzCcr5C2thu95iw41RaY1rOlx4vLNUWJH8iG3RVImgMth66uMhyvikJJJIGap_U3BfRfM_Dvh9RJ40w1E90n2Bx6xA9nvnOkXqybjPxbQOkPFdESYR-9ifY6gwwovgFgCA6wVrVfUoB98n5ZZ6RdpKgfcwb0800p5IlYqEpXOf2q583iziA9VqziVGrwToq5QPxNDnx2KplQX0JybRgZiECZNikkZwaYAtJE_JgI5kif5OYqYpEsBoiqQRnXbWrL8J1XiNPQZ4e72oNiU086j1Y-0oae7uEWVM6RHkcx3PMO_duYX_DcDrx3scFRgbBPVO_U-DJNpdGIbLlPsxFKxEKpuLGyH-rLvSLhNh7cZC5Shz_p1n2SFvbae1E3Ojdk0fbIOUyt132V9OofJRu9YXNvucVzxSSLd5bWMk8luENKwVCohUBCCRyltHVz5gpWPCdOoUnoJ98jBJk_x4OERS3P71ld-Km3F4KTyEjQtLcLgi5Jem9nU84rNWo9YIO1ktDrccy4oBcqSvYK7MVib8tqjgwirbFZdzk-8MiMrRVScDf-MRIr7LG2BYDtld_XG-vuyOxqiLuivxPCCBZvsbpWvG6-_T7QStaZyn6s70Cun7m6dcyhWMou_EUdCTmoVHaAZZILUarh_FrEoPxSs0s_r-uuwmVxrX0klrX9O6y__2Mn0BKYdTW1hCLJl8zCYLCTxBkQ

GET {{MuscleMemory.API_HostAddress}}/api/exercises?searchPhrase=
Authorization: Bearer {{token}}
###

POST {{MuscleMemory.API_HostAddress}}/api/exercises
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Allachy",
  "weight": 47.5,
  "reps": 8
}

###

POST {{MuscleMemory.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "test2@test.com",
    "password": "Password1!"
}

###

POST {{MuscleMemory.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "Password1!"
}

###

GET {{MuscleMemory.API_HostAddress}}/api/exercises/d8925775-f47c-4941-c91e-08dc5fc86b39
Authorization: Bearer {{token}}
###

PATCH {{MuscleMemory.API_HostAddress}}/api/exercises/ba021349-c1c2-4554-1d8a-08dc6313e2a4
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Weight": "90",
  "Reps": 1
}

###

DELETE {{MuscleMemory.API_HostAddress}}/api/exercises/49cfaa05-6b74-4f87-c0f2-08dc613be629
Authorization: Bearer {{token}}
###

POST {{MuscleMemory.API_HostAddress}}/api/identity/userRole/premium
Content-Type: application/json

{
  "UserEmail": "test@test.com"
}

###

POST {{MuscleMemory.API_HostAddress}}/api/identity/userRole/nonpremium
Authorization: Bearer {{tokenAdmin}}
Content-Type: application/json

{
  "UserEmail": "test@test.com"
}

###

PATCH {{MuscleMemory.API_HostAddress}}/api/identity
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nationality": "Poland"
}

###